EXECUTE ' GRANT SELECT ON TBL_MON_HORA_POS_NAC_' || TO_CHAR(SYSDATE, 'YYYYMM') || ' TO AppWeb ';
EXECUTE ' GRANT SELECT ON TBL_MON_HORA_POS_INT_' || TO_CHAR(SYSDATE, 'YYYYMM') || ' TO AppWeb ';
EXECUTE ' GRANT SELECT ON TBL_MON_HORA_ATM_NAC_' || TO_CHAR(SYSDATE, 'YYYYMM') || ' TO AppWeb ';
EXECUTE ' GRANT SELECT ON TBL_MON_HORA_ATM_INT_' || TO_CHAR(SYSDATE, 'YYYYMM') || ' TO AppWeb '; 